[tool.poetry]
name = "lark-experiments"
version = "0.1.0"
description = ""
authors = ["Drew O'Kane <drew.okane@climate.com>"]

[tool.poetry.dependencies]
python = "*"
lark-parser = "^0.6.4"
ipython = "^6.5"
toolz = "^0.9.0"
pytest-cov = "^2.6"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
